from core.utils import normalize_str
import copy
from typing import List, Dict, Union

def get_recipes() -> List[Dict[str, Union[str, List[Dict[str, str]]]]]:

    recipes = [
    {
        "label": "X1",
        "ingredients": [
        { "name": "Meat Scraps", "type": "Meat" },
        { "name": "Rubbery Jerky", "type": "Meat" },
        { "name": "Tough Meat", "type": "Meat" },
        { "name": "Chunky Rice", "type": "Bran" },
        { "name": "Furahiya Wheat", "type": "Bran" },
        { "name": "Mixed Beans", "type": "Bran" },
        { "name": "Bone Taco", "type": "Fish" },
        { "name": "Clamchip", "type": "Fish" },
        { "name": "Scalefish", "type": "Fish" },
        { "name": "Oily Raisins", "type": "Fruit" },
        { "name": "Jungle Onion", "type": "Veggie" },
        { "name": "Pumpkin", "type": "Veggie" },
        { "name": "Twinshroom", "type": "Veggie" },
        { "name": "Powdered Cheese", "type": "Milk" },
        { "name": "Sticky Cream", "type": "Milk" },
        { "name": "Hopi", "type": "Drink" },
        ],
        "meals":[
        { "ingredient1": "Meat", "ingredient2": "Meat", "effect": "HP +10" },
        { "ingredient1": "Meat", "ingredient2": "Bran", "effect": "HP +10" },
        { "ingredient1": "Meat", "ingredient2": "Veggie", "effect": "Stm +25" },
        { "ingredient1": "Meat", "ingredient2": "Drink", "effect": "Atk (S)" },
        { "ingredient1": "Bran", "ingredient2": "Bran", "effect": "Stm +25" },
        { "ingredient1": "Bran", "ingredient2": "Fish", "effect": "HP +10" },
        { "ingredient1": "Bran", "ingredient2": "Fruit", "effect": "Ice +3" },
        { "ingredient1": "Fish", "ingredient2": "Fish", "effect": "Atk (S)" },
        { "ingredient1": "Fish", "ingredient2": "Veggie", "effect": "Stm +25" },
        { "ingredient1": "Fish", "ingredient2": "Drink", "effect": "Def +10" },
        { "ingredient1": "Fruit", "ingredient2": "Veggie", "effect": "HP +20" },
        { "ingredient1": "Fruit", "ingredient2": "Milk", "effect": "Stm +25" },
        { "ingredient1": "Veggie", "ingredient2": "Veggie", "effect": "Def +10" },
        ],
    },
    {
        "label": "X2",
        "ingredients": [
        { "name": "Cubesteak", "type": "Meat" },
        { "name": "Spicy Sausage", "type": "Meat" },
        { "name": "Wild Bacon", "type": "Meat" },
        { "name": "Hardtack", "type": "Bran" },
        { "name": "Snowy Rice", "type": "Bran" },
        { "name": "Snake Salmon", "type": "Fish" },
        { "name": "Tuna Head", "type": "Fish" },
        { "name": "Fruity Jam", "type": "Fruit" },
        { "name": "Northern Orange", "type": "Fruit" },
        { "name": "Mild Herb", "type": "Veggie" },
        { "name": "Sliced Cactus", "type": "Veggie" },
        { "name": "Spotted Onion", "type": "Veggie" },
        { "name": "Young Potato", "type": "Veggie" },
        { "name": "Aged Cheest", "type": "Milk" },
        { "name": "Carefree Yogurt", "type": "Milk" },
        { "name": "Furahiya Cola", "type": "Drink" }
        ],
        "meals": [
        { "ingredient1": "Meat", "ingredient2": "Meat", "effect": "HP +20" },
        { "ingredient1": "Meat", "ingredient2": "Bran", "effect": "Def +15" },
        { "ingredient1": "Meat", "ingredient2": "Fruit", "effect": "Fir +3" },
        { "ingredient1": "Meat", "ingredient2": "Drink", "effect": "HP +10" },
        { "ingredient1": "Bran", "ingredient2": "Bran", "effect": "Stm +25" },
        { "ingredient1": "Bran", "ingredient2": "Fish", "effect": "HP +20" },
        { "ingredient1": "Bran", "ingredient2": "Veggie", "effect": "Atk (S)" },
        { "ingredient1": "Bran", "ingredient2": "Drink", "effect": "HP +10 Thn +3" },
        { "ingredient1": "Fish", "ingredient2": "Fish", "effect": "Atk (S)" },
        { "ingredient1": "Fish", "ingredient2": "Drink", "effect": "Stm +25" },
        { "ingredient1": "Fruit", "ingredient2": "Veggie", "effect": "HP +10 Def +10" },
        { "ingredient1": "Fruit", "ingredient2": "Milk", "effect": "Wtr +3" },
        { "ingredient1": "Veggie", "ingredient2": "Veggie", "effect": "Def +10" },
        { "ingredient1": "Veggie", "ingredient2": "Drink", "effect": "Stm +25" },
        { "ingredient1": "Milk", "ingredient2": "Milk", "effect": "Stm +25 Atk (S)" },
        { "ingredient1": "Milk", "ingredient2": "Drink", "effect": "Ice +3" }
        ],
    },
    {
        "label": "X3",
        "ingredients":[
        { "name": "Great Mutton", "type": "Meat" },
        { "name": "Juicy Rib Roast", "type": "Meat" },
        { "name": "Meatwagon", "type": "Meat" },
        { "name": "Kut Beans", "type": "Bran" },
        { "name": "Tasty Rice", "type": "Bran" },
        { "name": "Warwheat", "type": "Bran" },
        { "name": "Curved Shrimp", "type": "Fish" },
        { "name": "Horseshoe Crab", "type": "Fish" },
        { "name": "Spiky Blowfish", "type": "Fish" },
        { "name": "Frozen Apples", "type": "Fruit" },
        { "name": "Cudgel Onion", "type": "Veggie" },
        { "name": "Spicy Carrots", "type": "Veggie" },
        { "name": "Western Parsley", "type": "Veggie" },
        { "name": "Buffalo Butter", "type": "Milk" },
        { "name": "Chili Cheese", "type": "Milk" },
        { "name": "Panish", "type": "Drink" }
        ],
        "meals": [
        { "ingredient1": "Meat", "ingredient2": "Meat", "effect": "HP +20" },
        { "ingredient1": "Meat", "ingredient2": "Fish", "effect": "Thn +3" },
        { "ingredient1": "Meat", "ingredient2": "Fruit", "effect": "Atk (L)" },
        { "ingredient1": "Meat", "ingredient2": "Veggie", "effect": "HP +10 Atk (S)" },
        { "ingredient1": "Bran", "ingredient2": "Bran", "effect": "Stm +25" },
        { "ingredient1": "Bran", "ingredient2": "Veggie", "effect": "Stm +50" },
        { "ingredient1": "Bran", "ingredient2": "Milk", "effect": "Stm +25 Def +10" },
        { "ingredient1": "Bran", "ingredient2": "Drink", "effect": "Def +15 Wtr +3" },
        { "ingredient1": "Fish", "ingredient2": "Fish", "effect": "Atk (S)" },
        { "ingredient1": "Fish", "ingredient2": "Fruit", "effect": "Stm +25 Fir +3" },
        { "ingredient1": "Fish", "ingredient2": "Milk", "effect": "HP +30" },
        { "ingredient1": "Fruit", "ingredient2": "Drink", "effect": "Atk (S)" },
        { "ingredient1": "Veggie", "ingredient2": "Veggie", "effect": "Def +10" },
        { "ingredient1": "Veggie", "ingredient2": "Milk", "effect": "HP +10 Def +15" },
        { "ingredient1": "Milk", "ingredient2": "Milk", "effect": "HP +20 Ice +3" },
        ],
    },
    {
        "label": "X4",
        "ingredients": [
        { "name": "Dragon Foot", "type": "Meat" },
        { "name": "Gator Ribmeat", "type": "Meat" },
        { "name": "Princess Pork", "type": "Meat" },
        { "name": "Ancient Beans", "type": "Bran" },
        { "name": "Kokoto Rice", "type": "Bran" },
        { "name": "Megabagel", "type": "Bran" },
        { "name": "King Squid", "type": "Fish" },
        { "name": "Queen Shrimp", "type": "Fish" },
        { "name": "Pink Caviar", "type": "Fish" },
        { "name": "Burning Mango", "type": "Fruit" },
        { "name": "Lifejam", "type": "Fruit" },
        { "name": "Cannon Lettuce", "type": "Veggie" },
        { "name": "Rare Onion", "type": "Veggie" },
        { "name": "Scented Celery", "type": "Veggie" },
        { "name": "Royale Cheese", "type": "Milk" },
        { "name": "Blessed Wine", "type": "Drink" }
        ],
        "meals": [
        { "ingredient1": "Meat", "ingredient2": "Meat", "effect": "HP +30" },
        { "ingredient1": "Meat", "ingredient2": "Fish", "effect": "Stm +25 Wtr +5" },
        { "ingredient1": "Meat", "ingredient2": "Fruit", "effect": "Atk (S) Fir +5" },
        { "ingredient1": "Meat", "ingredient2": "Milk", "effect": "HP +40" },
        { "ingredient1": "Meat", "ingredient2": "Drink", "effect": "Def +10 Ice +5" },
        { "ingredient1": "Bran", "ingredient2": "Bran", "effect": "Stm +50" },
        { "ingredient1": "Bran", "ingredient2": "Veggie", "effect": "Stm +25 Atk (S)" },
        { "ingredient1": "Bran", "ingredient2": "Milk", "effect": "HP +30 Atk (S)" },
        { "ingredient1": "Fish", "ingredient2": "Fish", "effect": "Atk (L)" },
        { "ingredient1": "Fish", "ingredient2": "Fruit", "effect": "Def +20" },
        { "ingredient1": "Fish", "ingredient2": "Veggie", "effect": "HP +20 Drg +3" },
        { "ingredient1": "Fish", "ingredient2": "Milk", "effect": "Def +10 Thn +5" },
        { "ingredient1": "Fruit", "ingredient2": "Fruit", "effect": "HP +10 Atk (L)" },
        { "ingredient1": "Fruit", "ingredient2": "Veggie", "effect": "Stm +50" },
        { "ingredient1": "Fruit", "ingredient2": "Drink", "effect": "HP +20 Def +15" },
        { "ingredient1": "Veggie", "ingredient2": "Veggie", "effect": "Def +15" },
        { "ingredient1": "Veggie", "ingredient2": "Drink", "effect": "HP +40" },
        { "ingredient1": "Milk", "ingredient2": "Drink", "effect": "HP +20 Stm +25" }
        ],
    },
    {
        "label": "X5",
        "ingredients": [
        { "name": "Bigmeat", "type": "Meat" },
        { "name": "Dragon Head", "type": "Meat" },
        { "name": "Dragon Tail", "type": "Meat" },
        { "name": "King Turkey", "type": "Meat" },
        { "name": "Gold Rice", "type": "Bran" },
        { "name": "Heaven Bread", "type": "Bran" },
        { "name": "Sould Beans", "type": "Bran" },
        { "name": "1000-Year Crab", "type": "Fish" },
        { "name": "Crimson Seabream", "type": "Fish" },
        { "name": "Hairy Tuna", "type": "Fish" },
        { "name": "Emerald Durian", "type": "Fruit" },
        { "name": "Demonshroom", "type": "Veggie" },
        { "name": "Fatty Tomato", "type": "Veggie" },
        { "name": "King Truffle", "type": "Veggie" },
        { "name": "Kirin Cheese", "type": "Milk" },
        { "name": "Goldenfish Brew", "type": "Drink" }
        ],
        "meals": [
        { "ingredient1": "Meat", "ingredient2": "Meat", "effect": "HP +30" },
        { "ingredient1": "Meat", "ingredient2": "Fish", "effect": "HP +20 Stm +50" },
        { "ingredient1": "Meat", "ingredient2": "Veggie", "effect": "HP +40 Atk (L)" },
        { "ingredient1": "Meat", "ingredient2": "Milk", "effect": "Stm +25 Def +15" },
        { "ingredient1": "Meat", "ingredient2": "Drink", "effect": "Atk (S) Fir +5" },
        { "ingredient1": "Bran", "ingredient2": "Bran", "effect": "Stm +50" },
        { "ingredient1": "Bran", "ingredient2": "Fish", "effect": "HP +40 Def +20" },
        { "ingredient1": "Bran", "ingredient2": "Fruit", "effect": "HP +30 Stm +25" },
        { "ingredient1": "Bran", "ingredient2": "Veggie", "effect": "Stm +25 Atk (S)" },
        { "ingredient1": "Bran", "ingredient2": "Drink", "effect": "HP +20 Wtr +20" },
        { "ingredient1": "Fish", "ingredient2": "Fish", "effect": "Atk (L)" },
        { "ingredient1": "Fish", "ingredient2": "Fruit", "effect": "Stm +50 Def +10" },
        { "ingredient1": "Fish", "ingredient2": "Veggie", "effect": "Def +10 Ice +5" },
        { "ingredient1": "Fruit", "ingredient2": "Fruit", "effect": "-----------" },
        { "ingredient1": "Fruit", "ingredient2": "Milk", "effect": "HP +50 Drg +5" },
        { "ingredient1": "Fruit", "ingredient2": "Drink", "effect": "Atk (S) Thn 5" },
        { "ingredient1": "Veggie", "ingredient2": "Veggie", "effect": "Def +15" },
        { "ingredient1": "Veggie", "ingredient2": "Milk", "effect": "Stm +25 Def +20" },
        { "ingredient1": "Milk", "ingredient2": "Milk", "effect": "-----------" },
        { "ingredient1": "Milk", "ingredient2": "Drink", "effect": "HP +50 Stm +50" }
        ],
    },
    ]

    _recipes = copy.deepcopy(recipes)
    for recipe in _recipes:
        for ingredient in recipe["ingredients"]:
            ingredient.update({"norm_name": normalize_str(ingredient["name"])})
    return _recipes